export const DEFAULT_STEPS = [
  {
    stepNumber: 1,
    title: 'Order Confirmed',
    description: 'Order has been received and confirmed. Purchase order documents are verified.',
    requiresApproval: false,
    canBeSkipped: false,
    allowedUploaders: ['super_admin', 'admin'],
    allowedApprovers: [],
    uploadTypes: ['Purchase Order'],
    notifyRoles: [],
    colour: '#003DA5',
  },
  {
    stepNumber: 2,
    title: 'Sample & Fit Range',
    description: 'Samples prepared for review and approval.',
    requiresApproval: true,
    canBeSkipped: true,
    allowedUploaders: ['super_admin', 'admin'],
    allowedApprovers: ['super_admin', 'admin'],
    uploadTypes: ['Sample Photos', 'Fit Notes'],
    notifyRoles: [],
    colour: '#C9A84C',
  },
  {
    stepNumber: 3,
    title: 'Design Sign-Off',
    description: 'Final artwork and design files submitted for approval before production.',
    requiresApproval: true,
    canBeSkipped: false,
    allowedUploaders: ['super_admin', 'admin'],
    allowedApprovers: ['super_admin', 'admin'],
    uploadTypes: ['CAD Files', 'Mockups', 'Artwork'],
    notifyRoles: [],
    colour: '#C9A84C',
  },
  {
    stepNumber: 4,
    title: 'Fabric & CMT',
    description: 'Fabric procurement and cut, make, trim production phase.',
    requiresApproval: false,
    canBeSkipped: false,
    allowedUploaders: ['super_admin', 'admin'],
    allowedApprovers: [],
    uploadTypes: ['Fabric Specs', 'Production Photos'],
    notifyRoles: [],
    colour: '#003DA5',
  },
  {
    stepNumber: 5,
    title: 'Print, Embroidery & QC',
    description: 'Printing, embroidery, quality control, and final delivery preparation.',
    requiresApproval: false,
    canBeSkipped: false,
    allowedUploaders: ['super_admin', 'admin'],
    allowedApprovers: [],
    uploadTypes: ['QC Photos', 'Delivery Note'],
    notifyRoles: [],
    colour: '#003DA5',
  },
]
