export const DEFAULT_STEPS = [
  {
    stepNumber: 1,
    title: 'Order Confirmed',
    description: 'Order has been received and confirmed. Purchase order documents are verified.',
    requiresApproval: false,
    canBeSkipped: false,
    allowedUploaders: ['super_admin', 'admin'],
    allowedApprovers: [],
    uploadTypes: ['Purchase Order'],
    notifyRoles: ['admin'],
    colour: '#003DA5',
  },
  {
    stepNumber: 2,
    title: 'Sample & Fit Range',
    description: 'Distinctive Choice prepares samples for university review and approval.',
    requiresApproval: true,
    canBeSkipped: true,
    allowedUploaders: ['production', 'super_admin'],
    allowedApprovers: ['admin', 'university_staff'],
    uploadTypes: ['Sample Photos', 'Fit Notes'],
    notifyRoles: ['admin', 'university_staff'],
    colour: '#C9A84C',
  },
  {
    stepNumber: 3,
    title: 'Design Sign-Off',
    description: 'Final artwork and design files submitted for university approval before production.',
    requiresApproval: true,
    canBeSkipped: false,
    allowedUploaders: ['production', 'super_admin'],
    allowedApprovers: ['admin', 'super_admin'],
    uploadTypes: ['CAD Files', 'Mockups', 'Artwork'],
    notifyRoles: ['admin'],
    colour: '#C9A84C',
  },
  {
    stepNumber: 4,
    title: 'Fabric & CMT',
    description: 'Fabric procurement and cut, make, trim production phase.',
    requiresApproval: false,
    canBeSkipped: false,
    allowedUploaders: ['production', 'super_admin'],
    allowedApprovers: [],
    uploadTypes: ['Fabric Specs', 'Production Photos'],
    notifyRoles: ['admin'],
    colour: '#003DA5',
  },
  {
    stepNumber: 5,
    title: 'Print, Embroidery & QC',
    description: 'Printing, embroidery, quality control, and final delivery preparation.',
    requiresApproval: false,
    canBeSkipped: false,
    allowedUploaders: ['production', 'super_admin'],
    allowedApprovers: [],
    uploadTypes: ['QC Photos', 'Delivery Note'],
    notifyRoles: ['admin'],
    colour: '#003DA5',
  },
]
